# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"nvim" = ""
"gthumb" = ""
"menu" = "󰮫"
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = "󰗮"
".pdf" = ""
"slack" = ""
"spotify" = ""
"thunderbird" = "󰇮"
"psensor" = ""
"pavucontrol" = "󱡫"
"waydroid" = ""
"podman" = ""
"code" = "󰨞"
"calendar" = ""
"proton mail" = "󰇱"
"proton pass" = "󰯄"
"proton vpn" = "󰦝"

[other]
fallback_icon = ""
deduplicate_icons = true
separator = ": "
